name: Build and Deploy QuickNews

on:
  schedule:
    - cron: "0 7 * * *"   # US morning
    - cron: "0 15 * * *"  # JP morning
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us, jp]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensure gh-pages history is available

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py for ${{ matrix.region }}
        run: python main.py ${{ matrix.region }}

      - name: Add .nojekyll
        run: touch output/.nojekyll

      - name: Commit & push new edition
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f output/*
          git diff --cached --quiet || git commit -m "Add new QuickNews ${{ matrix.region }} edition"

          git pull --rebase origin gh-pages || true
          git push origin gh-pages
