name: Build and Deploy QuickNews

on:
  schedule:
    - cron: "0 7 * * *"   # US morning, 2AM EST (07:00 UTC)
    - cron: "0 15 * * *"  # JP morning, 9AM JST (15:00 UTC)
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  # required to push to gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: quicknews-${{ github.workflow }}-${{ matrix.region }}
      cancel-in-progress: false
    strategy:
      matrix:
        region: [us, jp]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure gh-pages history is available

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check schedule matches region
        id: check
        run: |
          HOUR=$(date -u +%H)
          MATCH=false

          if [ "${{ matrix.region }}" = "us" ] && [ "$HOUR" -eq 7 ]; then
            MATCH=true
          elif [ "${{ matrix.region }}" = "jp" ] && [ "$HOUR" -eq 15 ]; then
            MATCH=true
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "push" ]; then
            MATCH=true
          fi

          echo "match=$MATCH" >> $GITHUB_OUTPUT

      - name: Run main.py for ${{ matrix.region }}
        if: steps.check.outputs.match == 'true'
        run: python main.py ${{ matrix.region }}

      - name: Deploy to GitHub Pages (peaceiris)
        if: steps.check.outputs.match == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./newspaper
